version: 0.2

phases:
  install:
    commands:
      - echo Instalando Node 21 e npm...
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - npm install --loglevel=error
      - echo Construindo para o ambiente $ENVIRONMENT
      - ./build.sh $ENVIRONMENT  # Passa a variável de ambiente
      - echo $ENVIRONMENT
      #- REACT_APP_API_URL=https://hom-meddiflux.projeto-aws.com.br SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Rodando testes unitarios...
      - npm test
  