services:
  server:
#   env_file: .env
    build: .
    on:
      push:
        branches:
          - hom
          - prod
        container_name: bia
        ports:
          - 80:8080
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run:
          if [ "${{ github.ref }}" == "refs/heads/hom" ]; then
          docker build -t REACT_APP_API_URL --build-arg API_URL=http://homfmp.us-east-1.elasticbeanstalk.com 
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
          docker build -t REACT_APP_API_URL --build-arg API_URL=http://prodfmp.us-east-1.elasticbeanstalk.com
          fi