services:
  server:
    build:
      context: .
      args:
        - react_app_api_url=${API_URL}
    container_name: bia
    ports:
      - "80:8080"
    environment:
      - react_app_api_url=${API_URL}