version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências"
      - npm install
  pre_build:
    commands:
      - echo "Configurando variável de ambiente com base no branch"
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/main" ]; then
          export ENVIRONMENT="prod"
        else
          export ENVIRONMENT="hom"
        fi
      - echo "ENVIRONMENT definido como:" $ENVIRONMENT
  build:
    commands:
      - echo "Rodando o build.sh com ENVIRONMENT=$ENVIRONMENT"
      - ./build.sh