version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências"
      - npm install
  pre_build:
    commands:
      - echo "Verificando o tipo de push ou pull request"
      - echo "CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION"
      - |
        # Verificando se é um commit direto no 'main' ou se é um pull request
        if [[ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/main" ]]; then
          # Push direto para 'main', ambiente de homologação
          export ENVIRONMENT="hom"
          export REACT_APP_API_URL="https://prod.projeto-aws.com.br"
        elif [[ "$CODEBUILD_SOURCE_VERSION" == *"refs/pull"* ]]; then
          # Pull request para o 'main', ambiente de produção
          export ENVIRONMENT="prod"
          export REACT_APP_API_URL="https://prod.projeto-aws.com.br"
        else
          # Em caso de push para outro branch ou evento não esperado
          export ENVIRONMENT="hom"  # Pode ser outro comportamento aqui
          export REACT_APP_API_URL="https://hom.projeto-aws.com.br"
        fi
      - echo "ENVIRONMENT definido como:" $ENVIRONMENT
      - echo "REACT_APP_API_URL definido como:" $REACT_APP_API_URL
  build:
    commands:
      - echo "Rodando o build.sh com ENVIRONMENT=$ENVIRONMENT e REACT_APP_API_URL=$REACT_APP_API_URL"
      - ./build.sh  # Executa o build.sh usando as variáveis de ambiente configuradas
  post_build:
    commands:
      - echo "Build concluído"